name: CI
on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'
          
      - name: Run tests
        shell: bash
        run: |
          go mod tidy
          for pkg in $(go list ./... | grep -v "/cmd/"); do
            mkdir -p "${pkg}/coverage"
            go test -v -coverprofile="${pkg}/coverage.out" "$pkg"
          done
          
      - name: Merge coverage
        shell: bash
        run: |
          echo "mode: set" > full-coverage.out
          find . -name "coverage.out" -exec grep -h -v "^mode:" {} >> full-coverage.out \;
          go tool cover -func=full-coverage.out