name: CI
on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'
          
      - name: Run tests
        run: |
          go mod tidy
          for pkg in $(go list ./... | grep -v "/cmd/"); do
            go test -v -coverprofile=$pkg/coverage.out $pkg
          done
          
      - name: Merge coverage
        run: |
          echo "mode: set" > full-coverage.out
          find . -name "coverage.out" | while read file; do
            if [ -f "$file" ]; then
              grep -h -v "mode: set" "$file" >> full-coverage.out
            fi
          done
          go tool cover -func=full-coverage.out